name: Deploy Nuxt.js site to GitHub Pages

on:
  push:
    branches: ["master"] # Trigger on push to master
  workflow_dispatch: # Allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm
      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Build Nuxt app for static deployment
      - name: Build Nuxt app
        run: pnpm generate

      # Upload static site for GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: tanvir-portfolio.github.io

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
