name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["master"] # Trigger on push to master
  workflow_dispatch: # Allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Detect package manager (npm, yarn, pnpm)
      - name: Detect package manager
        id: detect-pm
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_OUTPUT
          elif [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
          else
            echo "manager=npm" >> $GITHUB_OUTPUT
          fi

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ steps.detect-pm.outputs.manager }}

      # Install dependencies
      - name: Install dependencies
        run: |
          case ${{ steps.detect-pm.outputs.manager }} in
            pnpm) corepack enable && pnpm install ;;
            yarn) yarn install ;;
            npm) npm ci ;;
          esac

      # Build Next.js app
      - name: Build Next.js
        run: |
          case ${{ steps.detect-pm.outputs.manager }} in
            pnpm) pnpm next build ;;
            yarn) yarn next build ;;
            npm) npx next build ;;
          esac

      # Upload static site for GitHub Pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
